### ISSUE TITLE
Yearly inflation is not 1% as described in whitepaper

### ISSUE THREAD

**Issue by aso118** [JohnDolittle/blackcoin-old#55]
As briefly discussed on the bitcointalk forum, the POS block reward of 1.5 BLK is not dynamic and yearly inflation will continue to decrease from the 1% per year as the coin continues to age.

https://bitcointalk.org/index.php?topic=469640.msg12860963#msg12860963

**Comment by bearsylla** [comment]
>  I find this current protocol an unacceptable deviation from the original source code.

I assume that by `original source code` you mean the earlier protocol that have dynamic reward. However, the v1 and v2 protocol actually does not gives 1% inflation as well. It will give 1% when no coinage is lost, which is only possible in theory. In reality, people make transactions and destroys coinage, therefore the 1% will not be achieved. Also, please bear in mind that there are coins that are lost due to missing privkeys, and those coins will never stake again, and thus making the inflation even less.

In protocol v3, it only distribute the reward to the people who stake, which provide a smooth inflation as opposed in earlier version, and it is a close estimate to 1%

If you look at this chart:
![inflation chart](http://i.imgur.com/tkjNaO7.png) 
[source](https://chainz.cryptoid.info/blk/#@inflation)

You can see that the inflation is smooth and annualized at slightly less 1% after the v3 switch. On the other hand, the earlier protocol remain at 0.2% to 0.4% annualized most of the time with occasional spikes to 5-11%

> Since the blocks already have a target of 64 seconds per block, the diffcultly readjusts according; therefore, the dynamic reward could possibly be calculated from the total number of coins.

This could be a good idea though

**Comment by JohnDolittle** [comment]
Will be 1% in Blacknet
